### ISSUE TITLE
Generic Key not found, the app told me to report this so please disregard if this has been resolved already; Thank you!

### ISSUE THREAD

**Issue by halfafk** [soleon/Percentage#20]
---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.1 has run into an error. You can help to fix this by:

1. Press Ctrl+C on this message

2. Report the copied error at https://github.com/soleon/Percentage/issues

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at Microsoft.Toolkit.Uwp.Notifications.ToastArguments.GetEnum[T](String key)

   at Percentage.App.Extensions.ToastNotificationExtensions.GetActionArgument(ToastArguments arguments)

   at Percentage.App.App.<.ctor>b__23_3(ToastNotificationActivatedEventArgsCompat toastArgs)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
---------------------------
OK   
---------------------------
![image](https://github.com/user-attachments/assets/4ab81e24-ebec-4034-be9a-44c726878283)

**Comment by halfafk** [comment]
It seems that the problem had disappeared by itself so I'm vaguely guessing the process ran a little too soon before it could verify some things. On the next app start the app ran normally and did not need any fixing. I will just leave this here but closed so that it may be looked at if it becomes a problem and reopened whenever. That is it and again, thank you!

**Comment by soleon** [comment]
@halfafk thank you for reporting this issue. This is also reported as issue #21 by another user. It is a bug I have identified, and a fix will be included in the upcoming updates.
