### ISSUE TITLE
KeyNotFoundException from ToastNotificationExtensions.GetActionArgument

### ISSUE THREAD

**Issue by nonztanon** [soleon/Percentage#21]
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.Toolkit.Uwp.Notifications.ToastArguments.GetEnum[T](String key)
   at Percentage.App.Extensions.ToastNotificationExtensions.GetActionArgument(ToastArguments arguments)
   at Percentage.App.App.<.ctor>b__23_3(ToastNotificationActivatedEventArgsCompat toastArgs)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by soleon** [comment]
This is fixed in release [2.1.2](https://github.com/soleon/Percentage/releases/tag/2.1.2).
