### ISSUE TITLE
GDI+ error when setting tray icon

### ISSUE THREAD

**Issue by vojtechBobcik** [soleon/Percentage#31]
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.

   at Wpf.Ui.Tray.Hicon.FromSource(ImageSource source)

   at Wpf.Ui.Tray.Controls.NotifyIcon.OnIconChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by soleon** [comment]
Hi @vojtechBobcik thank you for reporting this issue.

This error is fixed in version [2.1.4](https://github.com/soleon/Percentage/releases/tag/2.1.4). It will be available in Microsoft Store soon. Please update the app when it is available.

**Comment by soleon** [comment]
Closing this issue as it is duplicated with issue #25.
