### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by BipinSah** [soleon/Percentage#38]
---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.4 has run into an error. You can help to fix this by:

1. Press Ctrl+C on this message

2. Report the copied error at https://github.com/soleon/Percentage/issues

System.Runtime.InteropServices.COMException (0x88980003): MILERR_WIN32ERROR (0x88980003)

   at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by dkoek** [comment]
Same problem on the latest version:

---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.4 has run into an error. You can help to fix this by:

1. Press Ctrl+C on this message

2. Report the copied error at https://github.com/soleon/Percentage/issues



System.Runtime.InteropServices.COMException (0x88980003): MILERR_WIN32ERROR (0x88980003)

   at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at Percentage.App.App.Main()
---------------------------
OK   
---------------------------

**Comment by soleon** [comment]
Closing, duplicated with issue #35.
