### ISSUE TITLE
Error System.Runtime.InteropServices.COMException (0x88980003)

### ISSUE THREAD

**Issue by dragoib** [soleon/Percentage#41]
---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.4 has run into an error. 

System.Runtime.InteropServices.COMException (0x88980003): MILERR_WIN32ERROR (0x88980003)

   at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
ОК   
---------------------------

**Comment by soleon** [comment]
Duplicated with issue #35
