### ISSUE TITLE
COMException from NotifyIconExtensions.SetIcon

### ISSUE THREAD

**Issue by JagathesanNB** [soleon/Percentage#48]
---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.4 has run into an error. You can help to fix this by:

1. Press Ctrl+C on this message

2. Report the copied error at https://github.com/soleon/Percentage/issues

System.Runtime.InteropServices.COMException (0x88980003): MILERR_WIN32ERROR (0x88980003)

   at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.NotifyIconWindow.SetNotifyIconText(String text, Brush foreground)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by soleon** [comment]
Duplicated with issue #35.
