### ISSUE TITLE
found an error

### ISSUE THREAD

**Issue by hagamingpc** [soleon/Percentage#60]
Battery Percentage Icon version 2.1.6 has run into an error. 
System.Runtime.InteropServices.COMException (0x88980003): MILERR_WIN32ERROR (0x88980003)

   at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.NotifyIconWindow.SetNotifyIconText(String text, Brush foreground)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by hagamingpc** [comment]
![Screenshot 2025-01-01 190843](https://github.com/user-attachments/assets/b8ad7405-4fb9-4376-84e5-0792fa242289)
actual charge and battery percentage charge are not matching, still showing 93

**Comment by larsen0815** [comment]
> actual charge and app battery percentage are not matching, still showing 93

See #55

> MILERR_WIN32ERROR

What did you do before the error happened?

**Comment by soleon** [comment]
Duplicate of #55. Root cause is a HICON resource leak in WPF-UI's `NotifyIcon` (lepoco/wpfui#1313). Fixed in v2.1.10 via commit 7e85027 (`SafeNotifyIcon` calls `user32!DestroyIcon` on the prior HICON before each icon update). Please update — and reopen if it still happens on v2.1.10 or later.
